### ISSUE TITLE
Failure after adding Gaea

### ISSUE THREAD

**Issue by saipheblue** [BenjaTK/Gaea#101]
Once I enable plugin in project settings I got these errors:

 Godot Engine v4.1.2.stable.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
--- Debug adapter server started ---
--- GDScript language server started ---
  res://addons/gaea/generators/generator.gd:35 - Parse Error: Could not parse global class "GaeaGrid" from "res://addons/gaea/grid.gd".
  res://addons/gaea/generators/generator.gd:54 - Parse Error: Could not parse global class "GaeaGrid" from "res://addons/gaea/grid.gd".
  res://addons/gaea/generators/generator.gd:64 - Parse Error: Could not parse global class "GaeaGrid" from "res://addons/gaea/grid.gd".
  res://addons/gaea/generators/generator.gd:35 - Parse Error: Function "get_grid" cannot be used as getter because of its signature.
  res://addons/gaea/modifiers/2D/modifier_2d.gd:0 - Parse Error: Could not resolve class "Modifier".
  res://addons/gaea/modifiers/modifier.gd:30 - Parse Error: Could not parse global class "GaeaGrid" from "res://addons/gaea/grid.gd".
  res://addons/gaea/modifiers/modifier.gd:36 - Parse Error: Could not parse global class "GaeaGrid" from "res://addons/gaea/grid.gd".
  modules/gdscript/gdscript_compiler.cpp:2594 - Condition "!base->is_valid() && !base->reloading" is true. Returning: ERR_BUG

**Comment by saipheblue** [comment]
If it helps, tried downloading last two versions and none of them contains scene folder, while trying to download main it is also without tutorial scene.. only contents of addon folder

**Comment by BenjaTK** [comment]
Hey! What Godot version are you using?

**Comment by saipheblue** [comment]
v4.1.2.stable.official :)

**Comment by BenjaTK** [comment]
Yeah, the last versions are for 4.2 and up. I think v0.6.2 is the last 4.1 version.

**Comment by saipheblue** [comment]
Thank you ! It works :)
