### ISSUE TITLE
Can't generate tilemaps with heightmaps

### ISSUE THREAD

**Issue by TexanDoomGuy** [BenjaTK/Gaea#105]
everything works but heightmaps.

I'm getting the error:
res://addons/gaea/generators/2D/heightmap_generator/heightmap_generator_2d.gd:25 - Invalid set index 'seed' (on base: 'Nil') with value of type 'int'.

I made a recreation of my issue, with a HeightmapGenerator2D and a WalkerGenerator. They both have the same tilemap settings and TilemapGaeaRenderer.

Am I doing something wrong? There's no documentation for heightmaps so I used the same setup used in the [getting started tutorial](https://github.com/BenjaTK/Gaea/blob/main/docs/tutorials/getting_started.md).

project showcasing my issue:
[gewrwertgtwegr.zip](https://github.com/BenjaTK/Gaea/files/14861149/gewrwertgtwegr.zip)

**Comment by BenjaTK** [comment]
Was this fixed? Do you still need help?

**Comment by TexanDoomGuy** [comment]
Yeah, I fixed it. I just didn't have a terrain in my tilemap
