### ISSUE TITLE
extra collisions beside collidable tiles

### ISSUE THREAD

**Issue by SwiftGamer12** [BenjaTK/Gaea#107]
I am encountering a bug where if you have a tile map with collisions, when I generate a map using that tile map there are extra collisions beside collidable tiles. This happens to every 2d generator and I have tried to fix it with no success. Is this a bug or is there something I am doing wrong?

**Comment by SwiftGamer12** [comment]
If this helps my tiles are 32 by 32 pixels

**Comment by BenjaTK** [comment]
Sorry for being so late, but could you explain further with screenshots?

**Comment by SwiftGamer12** [comment]
https://github.com/BenjaTK/Gaea/assets/166310634/586fc12f-7a47-47d2-8565-fb06b0e10f1a
This is what I mean. I'm only supposed to collide with the white tiles, but I am also colliding with surrounding black tiles as well. I'm not sure if I am doing something wrong or if it is a bug.

**Comment by BenjaTK** [comment]
Seems to me like a project problem. I think you're not colliding with black tiles but the collision shape of your player isn't aligning with the player's sprite or the tile's collision shape isn't a square. Maybe turn on "Visible Collision Shapes"?

**Comment by SwiftGamer12** [comment]
![Screenshot 2024-05-03 203656](https://github.com/BenjaTK/Gaea/assets/166310634/75423abd-2b41-47cf-9b3a-d36871ebc562)

This is an earlier prototype but the generation works basically the same. As you can see, some white tiles are given black tile collisions. All of the unintentionally collidable white tiles are neighbors of black tiles. Do you have any idea on how to fix this?
