### ISSUE TITLE
ChunkLoader3D causes "Out of bounds get index '0'" error when "load_on_ready" is set to true and generator's "infinite" setting is set to false.

### ISSUE THREAD

**Issue by cullumi** [BenjaTK/Gaea#117]
The simple solution ( implemented in PR #118 ) is copying the following warning/early return from it's _process method up to _ready:
```
if generator.settings.get("infinite") == false:
	push_warning("Generator's settings at %s has infinite disabled, can't generate chunks." % generator.name)
	return
```

However, this error doesn't come up for the very similar ChunkLoader2D, so I'm making an issue in case the real issue lies in the HeightmapGenerator3D's initialization.

**Comment by BenjaTK** [comment]
Ok, it seems to be a problem with the `has_cell` method. It was checking a layer that didn't exist, so just adding a `grid.has(layer)` check fixes it.

**Comment by BenjaTK** [comment]
I've also removed the check for `infinite` enabled since you should be able to use ChunkLoaders on finite worlds.
