### ISSUE TITLE
Combine multiple noises to e.g. build biomes

### ISSUE THREAD

**Issue by AlunamB** [BenjaTK/Gaea#125]
It would be cool if I could combine multiple noises like this : https://www.youtube.com/watch?v=zoE-mosUJ-I&t=615s
It seems like this is not possibel at the moment. The current NoiseGenerator is a OneNoiseGenerator but a MultiNoiseGenerator would solve e.g. the biomes problem.
For a MultiNoiseGenerator:
I would try to separate the tiles (NoiseGeneratorData) from the noise settings. The MultiNoiseGenerator would hold the tiles (liek currently) and for each tile also which noise should be used in which range (like an extended version of the thresholds with min & max). 
The MultiNoiseGenerator would have multiple child nodes for different noises.

**Comment by BenjaTK** [comment]
I think this could be a cool addition but would require some work to make it fit with the plugin. I'll look into it.
