### ISSUE TITLE
I'm curious, how optimised is gaea

### ISSUE THREAD

**Issue by Derpysphere** [BenjaTK/Gaea#128]
And does it have a 3D world generator?

**Comment by BenjaTK** [comment]
This isn't really an issue, you can join the Discord server to ask questions.

**Comment by Derpysphere** [comment]
Ahh, I see. Most repos, use the issues tab for issues and questions (giving the writer the ability to mark as issue or question). also not everybody has a discord, or wants one.

**Comment by BenjaTK** [comment]
Sorry, idk what I was thinking, I was pretty tired yesterday. Gaea is fairly optimized in some parts, and unoptimized in others. The most unoptimized nodes are marked as experimental, and are being worked on, but with the recent changes by @cullumi with Threaded versions of certain nodes the performance has gone up by a lot.

**Comment by Derpysphere** [comment]
Yeah no problem, and thanks, I think this tool is awesome.
