### ISSUE TITLE
Update to Godot 4.3 (TileMapLayer)

### ISSUE THREAD

**Issue by DinoMC** [BenjaTK/Gaea#136]
I know 4.3 isn't out yet but is there currently a way I can assign a TileMapLayer node to a generator rather than a Tilemap node? Couldn't find any info about this

**Comment by BenjaTK** [comment]
That's coming as soon as 4.3 is released fully.

**Comment by DinoMC** [comment]
Thanks!
In the meantime, if anyone else looking for info land on this issue, I managed to get all demos* to work with a few changes to gaea/renderers/2D/tilemap_gaea_renderer.gd : 

Changes the following lines  (currently 10, 39-40, 53, 64):
```
@export var tile_map: TileMap :
...
for l in range(tile_map.get_layers_count()):
	tile_map.call_thread_safe("erase_cell", l, Vector2i(x, y))
...
tile_info.tilemap_layer, tile, tile_info.source_id,
...
tile_info.tilemap_layer, terrains[tile_info],
```
To : 
```
@export var tile_map: TileMapLayer :
...
#for l in range(tile_map.get_layers_count()):
	tile_map.call_thread_safe("erase_cell", Vector2i(x, y))
...
tile, tile_info.source_id,
...
terrains[tile_info],
```

*except for the wave_function_2D demo but even with a regular Tilemap I can't get it to work so it seems to be an issue with 4.3 and not TileMapLayer nodes
