### ISSUE TITLE
Missing parameters in signals

### ISSUE THREAD

**Issue by AeolianTheComposer** [BenjaTK/Gaea#138]
The signal "chunk_rendered" in ThreadedTilemapGaeaRenderer doesn't return chunk_position
![image](https://github.com/user-attachments/assets/c53ebe4c-b9c2-4710-b959-0bd80545bff1)

**Comment by AeolianTheComposer** [comment]
Love the addon btw :3

**Comment by BenjaTK** [comment]
Thanks for letting me know!
