### ISSUE TITLE
Broken link on github pages

### ISSUE THREAD

**Issue by realskyquest** [BenjaTK/Gaea#143]
I was reading about this plugin on the github pages and found a broken link that is supposed to lead to getting started, I'm using Floorp as my browser which is a fork of Firefox.

The page which has the broken link is generators/walker

https://benjatk.github.io/Gaea/#/generators/walker

![image](https://github.com/user-attachments/assets/91e98728-1672-46f8-8951-57338656b1db)

**Comment by BenjaTK** [comment]
Ah, thanks for that, I'll change it
