### ISSUE TITLE
Trying to generate Terrain Sets through NoiseGenerator, but it leaves gaps between terrains.

### ISSUE THREAD

**Issue by bren-10** [BenjaTK/Gaea#149]
I'm probably just missing something, but I can't seem to generate noise where the terrains link (like they do when drawing manually). No matter the tileset or the terrain set setup, I'm always left with blank tiles between terrains:

![image](https://github.com/user-attachments/assets/0fc44e85-73b7-4c51-937f-b64d8be2cede)

My tileset setup:

![image](https://github.com/user-attachments/assets/f2361ae5-dfaf-41ab-b268-0aa259ca3273)
(Original):
![image](https://github.com/user-attachments/assets/6096eaba-b414-4953-9b75-88d8915cee7c)
![image](https://github.com/user-attachments/assets/c0b09ac2-3385-46f2-b324-14380c4e3ff0)

When I draw manually, the tiles come out perfectly. Thanks in advance for any assistance!

**Comment by BenjaTK** [comment]
I think I found a fix for this, could you try going to TilemapGaeaRenderer and add a "false" parameter at the end of this function call?
![image](https://github.com/user-attachments/assets/9df4713e-746f-475e-b6a9-851180915a1c)

**Comment by bren-10** [comment]
That did it! Thanks so much!

**Comment by BenjaTK** [comment]
Great! I will push the fix then. This has been a problem for a while and I always thought it was a Godot problem, lol.
