### ISSUE TITLE
Crash on "Run Project" because of typo in "modifier.gd"

### ISSUE THREAD

**Issue by IrontMesdents** [BenjaTK/Gaea#154]
Hello, it's my fisrt bug report ever on Git, so sorry if I don't follow a certain etiquette.

While using Gaea in my godot project, there is a compile error related to the "modifier.gd" script and I think I found the issue.
In the Enum "FilterType" on line 10, the last filter is "ONLY_EMPTY_CELLS". However, on line 38, the "_passes_filter" function has an if statement with an filter type named "ONLY_EMPTY_TILES" that looks like a redundancy from line 47.

I commented it out and it seems to be launching the debug mode, but I'm not sure if I bypassed an issue by creating another or if it fixed it.

**Comment by BenjaTK** [comment]
This has been fixed in the latest release, I noticed it today.
