### ISSUE TITLE
Regression: v1.1.2 Breaks 3D Heightmap Generator

### ISSUE THREAD

**Issue by jeremiaszmazur** [BenjaTK/Gaea#156]
The merge **85ca9c7138363bb1d0ed7511d4d5fa1c0ac1fcfa** (in version v1.1.2) has introduced a bug that breaks the functionality of the 3D heightmap generator (from **demo**). This issue was not present in version v1.1.1.

Expected behavior:
The 3D heightmap generator should function correctly as it did in version v1.1.1.
![v11](https://github.com/user-attachments/assets/962cb1a8-c84d-4f57-a959-adac5afe3333)

Actual behavior:
The generator fails to produce the expected results in version v1.1.2.
![v112](https://github.com/user-attachments/assets/4640a377-3b18-4e43-a446-2cfa819506cf)

**Comment by BenjaTK** [comment]
Thanks for reporting, will give it a look
