### ISSUE TITLE
Git clone error

### ISSUE THREAD

**Issue by JekSun97** [BenjaTK/Gaea#168]
I can't clone the repository with `git clone https://github.com/BenjaTK/Gaea.git`

After 100% download I get an error:
![err](https://github.com/user-attachments/assets/42387854-a731-4e33-b990-bdbddf31c3c0)

`error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 5139 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
`

**Comment by BenjaTK** [comment]
This isn't really something on the repo side, more on the user side. Maybe try googling the error message and see what comes up.

**Comment by JekSun97** [comment]
The problem was that the command prompt was not run as administrator.
