### ISSUE TITLE
Error when running walker demo

### ISSUE THREAD

**Issue by Salodo** [BenjaTK/Gaea#17]
I was testing the demo scenes and everything worked worked fine except the walker generation
I got this error
![Screenshot from 2023-08-03 20-52-16](https://github.com/BenjaTK/Gaea/assets/101719871/92bbcfa9-2b38-4193-9f68-3fec13f09a87)
I did not modify anything for this to happen.

 My current version of Godot is 4.0.3 and I am using commit e345b7750f0a868127dddaffd0969e1bda711746 which is the latest at the current time.

**Comment by BenjaTK** [comment]
That's really weird, `Nil` what lmao. I'll check it out, thanks for submitting an issue!

**Comment by Salodo** [comment]
Sorry I tested this and realised that it works perfectly fine on godot 4.1 I dont know if the plugin is suppost to be 4.1 but it is not clarified in the reame

**Comment by BenjaTK** [comment]
Ah, well I'm using 4.1 Should probably clarify it! Still a really weird bug. Closing for now but lmk if it comes back.
