### ISSUE TITLE
How do I set up separate rendering of multiple TileMapLayer nodes in the Tile Map Layers variable of the TilemapGaeaRenderer node when generating tiles?

### ISSUE THREAD

**Issue by ice-ko** [BenjaTK/Gaea#172]
How to set multiple TileMapLayer nodes set in the Tile Map Layers variable of the TilemapGaeaRenderer node to render separately when generating tiles?

How to set the NoiseGenerator? For example: grass, beach, shallow sea, deep sea, etc. are rendered separately in TileMapLayer?

**Comment by BenjaTK** [comment]
It's an array, so the `tilemap_layer` in the TileInfo tells the renderer what layer to use (0 is the first in the array, etc.)

**Comment by ice-ko** [comment]
> It's an array, so the `tilemap_layer` in the TileInfo tells the renderer what layer to use (0 is the first in the array, etc.)它是一个数组，因此 TileInfo 中的 `tilemap_layer` 告诉渲染器要使用哪个层（0 是数组中的第一个层，依此类推）。

I am using TilemapTileInfo, how do I set it? I set the Layer property, but nothing happens

**Comment by ice-ko** [comment]
> It's an array, so the `tilemap_layer` in the TileInfo tells the renderer what layer to use (0 is the first in the array, etc.)

Thanks, I know how to set it up.
