### ISSUE TITLE
Add wiki

### ISSUE THREAD

**Issue by BenjaTK** [BenjaTK/Gaea#3]
Add documentation for nodes and modifiers. Both in Godot and Github.

**Comment by bitbrain** [comment]
I am happy to set  one up.

**Comment by BenjaTK** [comment]
That would help a lot! Do I have to give you permissions for something? I've never done a GitHub wiki.

**Comment by bitbrain** [comment]
@BenjaTK if you want I can set up something similar to this: https://bitbra.in/beehave which is done via [docsify](https://docsify.js.org) and would live in a [/docs](https://github.com/bitbrain/beehave/tree/godot-4.x/docs) folder.

The advantage is that people can raise PRs to improve the documentation, as the Github Wiki can only be edited by admins.

**Comment by BenjaTK** [comment]
That looks great! I'd appreciate it.
