### ISSUE TITLE
Separating Generation and Rendering

### ISSUE THREAD

**Issue by titusio** [BenjaTK/Gaea#31]
I think generation and rendering should be different scripts. 
The Generator classes should only be responsible for generating a certain area (like implemented in #29). The actual tile placing could handle another script.

This approach will have some advantages in my opinion:
- Regenerating data each time would be unnecessary because the user could implement saving logic and the WIP chunk system could take advantage of unloading.
- The plugin will be more universal. When users could handle drawing by themself, more custom solutions will be possible because they won't be bound to TileMaps.

Feedback is appreciated!

**Comment by BenjaTK** [comment]
What do you think about having a subclass of TileMap called GeneratorTileMap? Instead of adding a new node, your TileMap will just be a GeneratorTileMap and automatically draw the tiles. Then, when we add 3D support, we can have something like a VoxelGeneratorRenderer.

Also, this will require changing the TileInfo resource a little bit. I think the TileInfo class should be empty, and then make some subclasses such as TilemapTileInfo and VoxelInfo. This way, if someone wants to add a new way to store data, they can just inherit TileInfo.

**Comment by titusio** [comment]
> Also, this will require changing the TileInfo resource a little bit. I think the TileInfo class should be empty, and then make some subclasses such as TilemapTileInfo and VoxelInfo. This way, if someone wants to add a new way to store data, they can just inherit TileInfo.

I like this idea because generators shouldn't care about the actual tiles and this would allow users to inject their own data in case they need a custom solution.

> What do you think about having a subclass of TileMap called GeneratorTileMap?
I don't know if adding a new subclass would be the right choice. Some users might already have a custom TileMap subclass which could be hard to integrate. A separate `Node` would be better IMO

**Comment by titusio** [comment]
I would do something like this:
- A `GridManager` would call the generator and store all the grid data.
- The `generate` functions return only the grid they generated.
- The `ChunkLoader` calls the `GridManager` instead of the Generator.
- The `GridManager` calls the a `GridDrawer`. This could be a connection to a TileMap or any other kind of drawing mechanism. 
- The `GridManager` could have a virtual call which allows users to save generated grid. We could a virtual function like `has_saved(chunk_position) -> bool` and `get_saved_chunk(chunk_position) -> Dictionary`.

**Comment by BenjaTK** [comment]
Idk, I feel like that's too many nodes. I don't think anything in Godot uses that many nodes.

**Comment by titusio** [comment]
If the `GridManager` handles the Chunk loading too, there would be 3 Gaea Nodes, the TileMap and the Chunk Loading Actor. I'm not sure if this is still overwhelming.

<img width="430" alt="Bildschirmfoto 2023-08-28 um 06 08 53" src="https://github.com/BenjaTK/Gaea/assets/80385479/311492e4-909b-427a-9fb7-7171d6e22582">

**Comment by BenjaTK** [comment]
What if the renderer was a resource? You could pass in a reference to the tilemap or whatever and draw with it. Maybe we have a GridManager (either Chunked or not), a Generator, and a Tilemap.

**Comment by titusio** [comment]
I think the renderer shouldn't be a resource because it influences the world directly (it just feels right lol). The generator could be a resource. Generation happens only once but drawing happens constantly.
