### ISSUE TITLE
Make a logo

### ISSUE THREAD

**Issue by BenjaTK** [BenjaTK/Gaea#5]
Something to do with Gaea, greek mythology, and procgen ofc.

**Comment by nathanhoad** [comment]
How about something like this?

![gaea](https://github.com/BenjaTK/Gaea/assets/78984/77e59193-15c2-4d4e-a8ac-43b1a2ebdc87)

**Comment by BenjaTK** [comment]
I like it! I just don't love the font and I think it could benefit from less shading/no shading.

**Comment by nathanhoad** [comment]
![gaea](https://github.com/BenjaTK/Gaea/assets/78984/313237b3-5732-4db2-acc1-5d63ea55e292)

**Comment by BenjaTK** [comment]
> ![gaea](https://github.com/BenjaTK/Gaea/assets/78984/313237b3-5732-4db2-acc1-5d63ea55e292)
> 

Could you upload the svg file, please?
