### ISSUE TITLE
Better threshold editor for NoiseGeneratorSettings

### ISSUE THREAD

**Issue by BenjaTK** [BenjaTK/Gaea#50]
Using Dictionaries is just really bad. I'll make a concept soon.

**Comment by squk** [comment]
Hey! I made this which I think will work as a substitute : https://github.com/squk/godot-dictionary-resource

**Comment by DaviD4Chirino** [comment]
I made a fork that uses a custom resource instead of a dictionary [https://github.com/BenjaTK/Gaea/pull/88](https://github.com/BenjaTK/Gaea/pull/88)
