### ISSUE TITLE
C# support

### ISSUE THREAD

**Issue by KirillSDev** [BenjaTK/Gaea#82]
Will there be C# support in the future?

**Comment by BenjaTK** [comment]
It would be cool, but I'm not a C# dev and it would not feasible for me to try to add official support since that would require rewriting the whole project. If someone else wants to do it, that would be great!

**Comment by thequeenbea** [comment]
i used unity for 3 years before switching to godot so i have plenty of experience with c#; maybe someday i'll try adding support
