### ISSUE TITLE
Can not get ChunkLoader3D to work

### ISSUE THREAD

**Issue by RAMENtheNOODLES** [BenjaTK/Gaea#96]
I am using v0.8.0 of Gaea, and I would like to have chunks generated on ready, but I cannot get the chunk loader to load in the chunks that the ChunkLoader3D creates. I attached a generator and an actor to it. It seems to generate chunks, as it takes a while to load, but it does not show any. I can provide images if needed. Is there a specific way I need to set this up?

**Comment by BenjaTK** [comment]
Could you show me the inspector for the nodes, please?

**Comment by RAMENtheNOODLES** [comment]
![image](https://github.com/BenjaTK/Gaea/assets/58859646/0a660479-55d0-48e6-a0ec-a4c784983f3b)
![image](https://github.com/BenjaTK/Gaea/assets/58859646/dfc8dcae-fa09-448f-9f9d-fb9ca7447f10)
![image](https://github.com/BenjaTK/Gaea/assets/58859646/b28d52c9-e1d2-4458-900d-40ff755651e0)

**Comment by BenjaTK** [comment]
Ah yeah, you're missing a GridMapRenderer. That's what draws the generation.

**Comment by RAMENtheNOODLES** [comment]
Ah, okay. That fixed it! Now, when it loads new chunks, it does not seem to be using the noise generator, and the new chunks are being generated at a lower y-level than the already generated chunks.

![image](https://github.com/BenjaTK/Gaea/assets/58859646/e03851a4-e5e8-48f7-ae9e-ffd1a4f2c4d3)

**Comment by RAMENtheNOODLES** [comment]
Nevermind, I believe it was not generating correctly due to the loading radius being set right.
